using System.Globalization;
using Microsoft.Extensions.Localization;

namespace OpenAlmatyIdeas;

public class SharedResource { }

public class AppStringLocalizer : IStringLocalizer<SharedResource>
{
    private static readonly Dictionary<string, string> _ru = new()
    {
        ["Nav.Proposals"] = "Предложения",
        ["Nav.Top"] = "Топ идей",
        ["Nav.Map"] = "Карта",
        ["Nav.About"] = "О проекте",
        ["Nav.AdminPanel"] = "⚙ Панель",
        ["Nav.NewProposal"] = "+ Предложение",
        ["Nav.MyProposals"] = "Мои предложения",
        ["Nav.Logout"] = "Выйти",
        ["Nav.Login"] = "Войти",
        ["Nav.Register"] = "Регистрация",

        ["Status.Pending"] = "На рассмотрении",
        ["Status.Accepted"] = "Принято",
        ["Status.Rejected"] = "Отклонено",
        ["Status.Implemented"] = "Реализовано",

        ["Footer.Text"] = "Платформа гражданских инициатив Алматы",

        ["Home.PageTitle"] = "Главная",
        ["Home.TagLine"] = "Гражданская платформа — Алматы",
        ["Home.HeroSubtitle"] = "Предлагайте идеи по улучшению города, голосуйте и следите за реализацией.",
        ["Home.SuggestIdea"] = "+ Предложить идею",
        ["Home.JoinUs"] = "Присоединиться",
        ["Home.ViewProposals"] = "Смотреть предложения →",
        ["Home.ViewProposalsPlain"] = "Смотреть предложения",
        ["Home.StatProposals"] = "Предложений",
        ["Home.StatDistricts"] = "Районов",
        ["Home.StatCategories"] = "Категорий",
        ["Home.RatingTag"] = "Рейтинг",
        ["Home.TopProposals"] = "Топ предложения",
        ["Home.TopSubtitle"] = "Самые поддерживаемые идеи горожан",
        ["Home.CoverageTag"] = "Охват",
        ["Home.DistrictsTitle"] = "Районы Алматы",
        ["Home.DistrictsSubtitle"] = "Все 8 административных районов города",
        ["Home.ProcessTag"] = "Процесс",
        ["Home.HowItWorks"] = "Как это работает?",
        ["Home.Step1Title"] = "Зарегистрируйтесь",
        ["Home.Step1Text"] = "Создайте аккаунт — это займёт меньше минуты",
        ["Home.Step2Title"] = "Подайте предложение",
        ["Home.Step2Text"] = "Опишите идею, укажите район и категорию",
        ["Home.Step3Title"] = "Голосуйте",
        ["Home.Step3Text"] = "Поддерживайте понравившиеся идеи горожан",
        ["Home.Step4Title"] = "Следите за результатом",
        ["Home.Step4Text"] = "Статус предложения обновляется администраторами",
        ["Home.JoinTag"] = "Присоединяйтесь",
        ["Home.CtaTitle"] = "Ваш голос важен для Алматы",
        ["Home.CtaSubtitle"] = "Зарегистрируйтесь, чтобы подавать предложения и голосовать за идеи горожан.",
        ["Home.SignUp"] = "Зарегистрироваться",

        ["Proposals.PageTitle"] = "Предложения",
        ["Proposals.Subtitle"] = "Идеи жителей Алматы по улучшению города",
        ["Proposals.NewBtn"] = "+ Новое предложение",
        ["Proposals.SearchPlaceholder"] = "🔍 Поиск по названию...",
        ["Proposals.AllDistricts"] = "Все районы",
        ["Proposals.AllCategories"] = "Все категории",
        ["Proposals.SortNew"] = "Новые",
        ["Proposals.SortPopular"] = "Популярные",
        ["Proposals.Apply"] = "Применить",
        ["Proposals.Reset"] = "✕ Сбросить",
        ["Proposals.NotFound"] = "Предложений не найдено.",
        ["Proposals.BeFirst"] = "Будьте первым!",
        ["Proposals.Shown"] = "Показано:",
        ["Proposals.ShownSuffix"] = "предложений",

        ["Proposal.Back"] = "← Все предложения",
        ["Proposal.Voting"] = "Голосование",
        ["Proposal.LoginToVote"] = "Войдите",
        ["Proposal.ToVote"] = ", чтобы проголосовать",
        ["Proposal.Info"] = "Информация",
        ["Proposal.Status"] = "Статус",
        ["Proposal.District"] = "Район",
        ["Proposal.Category"] = "Категория",
        ["Proposal.Author"] = "Автор",
        ["Proposal.Date"] = "Дата",
        ["Proposal.Edit"] = "✏ Редактировать",
        ["Proposal.Delete"] = "🗑 Удалить",
        ["Proposal.DeleteConfirm"] = "Удалить предложение?",
        ["Proposal.AdminResponses"] = "💬 Ответы администратора",

        ["NewProposal.Title"] = "Новое предложение",
        ["NewProposal.Subtitle"] = "Опишите вашу идею по улучшению города",
        ["NewProposal.NameLabel"] = "Название",
        ["NewProposal.NamePlaceholder"] = "Краткое название вашей идеи",
        ["NewProposal.DistrictLabel"] = "Район",
        ["NewProposal.DistrictDefault"] = "— Выберите район —",
        ["NewProposal.CategoryLabel"] = "Категория",
        ["NewProposal.CategoryDefault"] = "— Выберите категорию —",
        ["NewProposal.ShortDescLabel"] = "Краткое описание",
        ["NewProposal.ShortDescPlaceholder"] = "Кратко опишите вашу идею (отображается в списке)",
        ["NewProposal.FullDescLabel"] = "Полное описание",
        ["NewProposal.FullDescPlaceholder"] = "Подробно опишите предложение: проблему, решение, ожидаемый результат",
        ["NewProposal.Submit"] = "Отправить предложение",
        ["NewProposal.Cancel"] = "Отмена",

        ["EditProposal.Title"] = "Редактировать предложение",
        ["EditProposal.Subtitle"] = "Измените данные вашего предложения",
        ["EditProposal.SaveChanges"] = "Сохранить изменения",
        ["EditProposal.Cancel"] = "Отмена",

        ["Login.Title"] = "Вход",
        ["Login.Subtitle"] = "Войдите в свой аккаунт",
        ["Login.Username"] = "Имя пользователя",
        ["Login.Password"] = "Пароль",
        ["Login.RememberMe"] = "Запомнить меня",
        ["Login.Submit"] = "Войти",
        ["Login.NoAccount"] = "Нет аккаунта?",
        ["Login.SignUp"] = "Зарегистрироваться",

        ["Register.Title"] = "Регистрация",
        ["Register.Subtitle"] = "Присоединяйтесь к Open Almaty Ideas",
        ["Register.Username"] = "Имя пользователя",
        ["Register.Email"] = "Email",
        ["Register.Password"] = "Пароль",
        ["Register.ConfirmPassword"] = "Подтвердите пароль",
        ["Register.Submit"] = "Зарегистрироваться",
        ["Register.HaveAccount"] = "Уже есть аккаунт?",
        ["Register.Login"] = "Войти",

        ["Profile.Title"] = "Мои предложения",
        ["Profile.NewBtn"] = "+ Новое предложение",
        ["Profile.Empty"] = "У вас пока нет предложений",
        ["Profile.CreateFirst"] = "Создать первое предложение",
        ["Profile.ColName"] = "Название",
        ["Profile.ColDistrict"] = "Район",
        ["Profile.ColCategory"] = "Категория",
        ["Profile.ColStatus"] = "Статус",
        ["Profile.ColVotes"] = "Голоса",
        ["Profile.ColDate"] = "Дата",
        ["Profile.Total"] = "Всего:",
        ["Profile.TotalSuffix"] = "предложений",
        ["Profile.DeleteConfirm"] = "Удалить предложение?",

        ["Top.PageTitle"] = "Топ идей",
        ["Top.RatingTag"] = "Рейтинг",
        ["Top.Title"] = "🏆 Топ идей",
        ["Top.Subtitle"] = "Предложения с наибольшим количеством голосов",
        ["Top.NoVotes"] = "Голосований пока нет. Будьте первым!",

        ["Map.PageTitle"] = "Карта районов",
        ["Map.InteractiveTag"] = "Интерактивная карта",
        ["Map.Title"] = "🗺️ Карта районов Алматы",
        ["Map.Subtitle"] = "Выберите район, чтобы просмотреть идеи жителей",
        ["Map.IdeaWord1"] = "идея",
        ["Map.IdeaWord24"] = "идеи",
        ["Map.IdeaWordMany"] = "идей",
        ["Map.View"] = "Смотреть",

        ["About.PageTitle"] = "О проекте",
        ["About.Subtitle"] = "Гражданская платформа для улучшения города Алматы",
        ["About.MissionTag"] = "Миссия",
        ["About.MissionTitle"] = "Что такое Open Almaty Ideas?",
        ["About.MissionText"] = "это цифровая платформа гражданских инициатив, созданная для жителей Алматы. Мы верим, что лучшие идеи по улучшению города рождаются у тех, кто в нём живёт. Платформа даёт каждому горожанину голос — возможность предложить идею, поддержать других и видеть, как инициативы воплощаются в жизнь.",
        ["About.ProcessTag"] = "Процесс",
        ["About.ProcessTitle"] = "Как это работает?",
        ["About.Step1Title"] = "Зарегистрируйтесь",
        ["About.Step1Text"] = "Создайте аккаунт — это займёт меньше минуты",
        ["About.Step2Title"] = "Подайте предложение",
        ["About.Step2Text"] = "Опишите идею, укажите район и категорию",
        ["About.Step3Title"] = "Голосуйте",
        ["About.Step3Text"] = "Поддерживайте понравившиеся идеи других горожан",
        ["About.Step4Title"] = "Следите за результатом",
        ["About.Step4Text"] = "Администраторы рассматривают предложения и обновляют статус",
        ["About.CoverageTag"] = "Охват",
        ["About.DistrictsTitle"] = "Районы Алматы",
        ["About.DistrictsText"] = "Платформа охватывает все 8 административных районов города:",
        ["About.CategoriesTag"] = "Тематика",
        ["About.CategoriesTitle"] = "Категории предложений",
        ["About.LifecycleTag"] = "Жизненный цикл",
        ["About.StatusesTitle"] = "Статусы предложений",
        ["About.Status.Pending"] = "На рассмотрении",
        ["About.Status.PendingDesc"] = "Предложение получено и изучается",
        ["About.Status.Accepted"] = "Принято",
        ["About.Status.AcceptedDesc"] = "Идея одобрена к реализации",
        ["About.Status.Implemented"] = "Реализовано",
        ["About.Status.ImplementedDesc"] = "Предложение воплощено в жизнь",
        ["About.Status.Rejected"] = "Отклонено",
        ["About.Status.RejectedDesc"] = "Предложение не принято с объяснением причин",
        ["About.CtaTitle"] = "Присоединяйтесь к Open Almaty Ideas",
        ["About.CtaSubtitle"] = "Ваш голос важен для развития Алматы",
        ["About.SignUp"] = "Зарегистрироваться",
        ["About.ViewProposals"] = "Смотреть предложения",

        ["Admin.ToSite"] = "← На сайт",
        ["Admin.Logout"] = "Выйти",
        ["Admin.Management"] = "Управление",
        ["Admin.Home"] = "Главная",
        ["Admin.Proposals"] = "Предложения",
        ["Admin.Districts"] = "Районы",
        ["Admin.Categories"] = "Категории",
        ["Admin.DashboardTitle"] = "Панель администратора",
        ["Admin.ProposalsDesc"] = "Управление предложениями граждан",
        ["Admin.DistrictsDesc"] = "Управление районами города",
        ["Admin.CategoriesDesc"] = "Управление категориями предложений",
        ["Admin.Manage"] = "Управлять",
        ["Admin.ColId"] = "#",
        ["Admin.ColName"] = "Название",
        ["Admin.ColDistrict"] = "Район",
        ["Admin.ColCategory"] = "Категория",
        ["Admin.ColAuthor"] = "Автор",
        ["Admin.ColStatus"] = "Статус",
        ["Admin.ColDate"] = "Дата",
        ["Admin.ColActions"] = "Действия",
        ["Admin.ColCount"] = "Предложений",
        ["Admin.Edit"] = "Изменить",
        ["Admin.Delete"] = "Удалить",
        ["Admin.AddCategory"] = "+ Добавить категорию",
        ["Admin.AddDistrict"] = "+ Добавить район",
        ["Admin.DeleteProposalConfirm"] = "Удалить предложение?",
        ["Admin.DeleteCategoryConfirm"] = "Удалить категорию?",
        ["Admin.DeleteDistrictConfirm"] = "Удалить район?",
        ["Admin.EditProposalTitle"] = "Редактирование предложения",
        ["Admin.StatusLabel"] = "Статус",
        ["Admin.AdminResponse"] = "Ответ администратора (необязательно)",
        ["Admin.AdminResponsePlaceholder"] = "Введите комментарий к решению...",
        ["Admin.Save"] = "Сохранить",
        ["Admin.Cancel"] = "Отмена",
        ["Admin.NewCategory"] = "Новая категория",
        ["Admin.EditCategory"] = "Редактирование категории",
        ["Admin.NewDistrict"] = "Новый район",
        ["Admin.EditDistrict"] = "Редактирование района",
        ["Admin.AccessDeniedTitle"] = "Доступ запрещён",
        ["Admin.AccessDeniedText"] = "У вас нет прав для просмотра этой страницы.",
        ["Admin.ToHome"] = "На главную",
    };

    private static readonly Dictionary<string, string> _kk = new()
    {
        ["Nav.Proposals"] = "Ұсыныстар",
        ["Nav.Top"] = "Идеялар топы",
        ["Nav.Map"] = "Карта",
        ["Nav.About"] = "Жоба туралы",
        ["Nav.AdminPanel"] = "⚙ Панель",
        ["Nav.NewProposal"] = "+ Ұсыныс",
        ["Nav.MyProposals"] = "Менің ұсыныстарым",
        ["Nav.Logout"] = "Шығу",
        ["Nav.Login"] = "Кіру",
        ["Nav.Register"] = "Тіркелу",

        ["Status.Pending"] = "Қарастыруда",
        ["Status.Accepted"] = "Қабылданды",
        ["Status.Rejected"] = "Қабылданбады",
        ["Status.Implemented"] = "Іске асырылды",

        ["Footer.Text"] = "Алматы азаматтық бастамалар платформасы",

        ["Home.PageTitle"] = "Басты бет",
        ["Home.TagLine"] = "Азаматтық платформа — Алматы",
        ["Home.HeroSubtitle"] = "Қаланы жақсарту туралы идеяларыңызды ұсыныңыз, дауыс беріңіз және іске асырылуын қадағалаңыз.",
        ["Home.SuggestIdea"] = "+ Идея ұсыну",
        ["Home.JoinUs"] = "Қосылу",
        ["Home.ViewProposals"] = "Ұсыныстарды қарау →",
        ["Home.ViewProposalsPlain"] = "Ұсыныстарды қарау",
        ["Home.StatProposals"] = "Ұсыныстар",
        ["Home.StatDistricts"] = "Аудандар",
        ["Home.StatCategories"] = "Санаттар",
        ["Home.RatingTag"] = "Рейтинг",
        ["Home.TopProposals"] = "Топ ұсыныстар",
        ["Home.TopSubtitle"] = "Қала тұрғындарының ең қолдауға ие идеялары",
        ["Home.CoverageTag"] = "Қамту",
        ["Home.DistrictsTitle"] = "Алматы аудандары",
        ["Home.DistrictsSubtitle"] = "Қаланың барлық 8 әкімшілік ауданы",
        ["Home.ProcessTag"] = "Үрдіс",
        ["Home.HowItWorks"] = "Бұл қалай жұмыс істейді?",
        ["Home.Step1Title"] = "Тіркеліңіз",
        ["Home.Step1Text"] = "Аккаунт жасаңыз — бір минутқа дейін уақыт алады",
        ["Home.Step2Title"] = "Ұсыныс беріңіз",
        ["Home.Step2Text"] = "Идеяны сипаттаңыз, аудан мен санатты көрсетіңіз",
        ["Home.Step3Title"] = "Дауыс беріңіз",
        ["Home.Step3Text"] = "Қала тұрғындарының ұнаған идеяларын қолдаңыз",
        ["Home.Step4Title"] = "Нәтижені қадағалаңыз",
        ["Home.Step4Text"] = "Ұсыныс мәртебесін әкімшілер жаңартады",
        ["Home.JoinTag"] = "Қосылыңыз",
        ["Home.CtaTitle"] = "Сіздің дауысыңыз Алматы үшін маңызды",
        ["Home.CtaSubtitle"] = "Ұсыныстар беру және қала тұрғындарының идеяларына дауыс беру үшін тіркеліңіз.",
        ["Home.SignUp"] = "Тіркелу",

        ["Proposals.PageTitle"] = "Ұсыныстар",
        ["Proposals.Subtitle"] = "Алматы тұрғындарының қаланы жақсарту идеялары",
        ["Proposals.NewBtn"] = "+ Жаңа ұсыныс",
        ["Proposals.SearchPlaceholder"] = "🔍 Атауы бойынша іздеу...",
        ["Proposals.AllDistricts"] = "Барлық аудандар",
        ["Proposals.AllCategories"] = "Барлық санаттар",
        ["Proposals.SortNew"] = "Жаңалар",
        ["Proposals.SortPopular"] = "Танымалдар",
        ["Proposals.Apply"] = "Қолдану",
        ["Proposals.Reset"] = "✕ Тазалау",
        ["Proposals.NotFound"] = "Ұсыныс табылмады.",
        ["Proposals.BeFirst"] = "Бірінші болыңыз!",
        ["Proposals.Shown"] = "Көрсетілген:",
        ["Proposals.ShownSuffix"] = "ұсыныс",

        ["Proposal.Back"] = "← Барлық ұсыныстар",
        ["Proposal.Voting"] = "Дауыс беру",
        ["Proposal.LoginToVote"] = "Кіріңіз",
        ["Proposal.ToVote"] = ", дауыс беру үшін",
        ["Proposal.Info"] = "Ақпарат",
        ["Proposal.Status"] = "Мәртебе",
        ["Proposal.District"] = "Аудан",
        ["Proposal.Category"] = "Санат",
        ["Proposal.Author"] = "Автор",
        ["Proposal.Date"] = "Күні",
        ["Proposal.Edit"] = "✏ Өңдеу",
        ["Proposal.Delete"] = "🗑 Жою",
        ["Proposal.DeleteConfirm"] = "Ұсынысты жою керек пе?",
        ["Proposal.AdminResponses"] = "💬 Әкімші жауаптары",

        ["NewProposal.Title"] = "Жаңа ұсыныс",
        ["NewProposal.Subtitle"] = "Қаланы жақсарту идеяңызды сипаттаңыз",
        ["NewProposal.NameLabel"] = "Атауы",
        ["NewProposal.NamePlaceholder"] = "Идеяңыздың қысқаша атауы",
        ["NewProposal.DistrictLabel"] = "Аудан",
        ["NewProposal.DistrictDefault"] = "— Аудан таңдаңыз —",
        ["NewProposal.CategoryLabel"] = "Санат",
        ["NewProposal.CategoryDefault"] = "— Санат таңдаңыз —",
        ["NewProposal.ShortDescLabel"] = "Қысқаша сипаттама",
        ["NewProposal.ShortDescPlaceholder"] = "Идеяңызды қысқаша сипаттаңыз (тізімде көрсетіледі)",
        ["NewProposal.FullDescLabel"] = "Толық сипаттама",
        ["NewProposal.FullDescPlaceholder"] = "Ұсынысты толық сипаттаңыз: мәселе, шешім, күтілетін нәтиже",
        ["NewProposal.Submit"] = "Ұсынысты жіберу",
        ["NewProposal.Cancel"] = "Бас тарту",

        ["EditProposal.Title"] = "Ұсынысты өңдеу",
        ["EditProposal.Subtitle"] = "Ұсыныс деректерін өзгертіңіз",
        ["EditProposal.SaveChanges"] = "Өзгерістерді сақтау",
        ["EditProposal.Cancel"] = "Бас тарту",

        ["Login.Title"] = "Кіру",
        ["Login.Subtitle"] = "Аккаунтыңызға кіріңіз",
        ["Login.Username"] = "Пайдаланушы аты",
        ["Login.Password"] = "Құпия сөз",
        ["Login.RememberMe"] = "Мені есте сақтау",
        ["Login.Submit"] = "Кіру",
        ["Login.NoAccount"] = "Аккаунт жоқ па?",
        ["Login.SignUp"] = "Тіркелу",

        ["Register.Title"] = "Тіркелу",
        ["Register.Subtitle"] = "Open Almaty Ideas жобасына қосылыңыз",
        ["Register.Username"] = "Пайдаланушы аты",
        ["Register.Email"] = "Email",
        ["Register.Password"] = "Құпия сөз",
        ["Register.ConfirmPassword"] = "Құпия сөзді растаңыз",
        ["Register.Submit"] = "Тіркелу",
        ["Register.HaveAccount"] = "Аккаунт бар ма?",
        ["Register.Login"] = "Кіру",

        ["Profile.Title"] = "Менің ұсыныстарым",
        ["Profile.NewBtn"] = "+ Жаңа ұсыныс",
        ["Profile.Empty"] = "Сізде әлі ұсыныс жоқ",
        ["Profile.CreateFirst"] = "Бірінші ұсынысты жасау",
        ["Profile.ColName"] = "Атауы",
        ["Profile.ColDistrict"] = "Аудан",
        ["Profile.ColCategory"] = "Санат",
        ["Profile.ColStatus"] = "Мәртебе",
        ["Profile.ColVotes"] = "Дауыстар",
        ["Profile.ColDate"] = "Күні",
        ["Profile.Total"] = "Барлығы:",
        ["Profile.TotalSuffix"] = "ұсыныс",
        ["Profile.DeleteConfirm"] = "Ұсынысты жою керек пе?",

        ["Top.PageTitle"] = "Идеялар топы",
        ["Top.RatingTag"] = "Рейтинг",
        ["Top.Title"] = "🏆 Идеялар топы",
        ["Top.Subtitle"] = "Ең көп дауыс жинаған ұсыныстар",
        ["Top.NoVotes"] = "Дауыс беру әлі жоқ. Бірінші болыңыз!",

        ["Map.PageTitle"] = "Аудандар картасы",
        ["Map.InteractiveTag"] = "Интерактивті карта",
        ["Map.Title"] = "🗺️ Алматы аудандарының картасы",
        ["Map.Subtitle"] = "Тұрғындардың идеяларын қарау үшін аудан таңдаңыз",
        ["Map.IdeaWord1"] = "идея",
        ["Map.IdeaWord24"] = "идея",
        ["Map.IdeaWordMany"] = "идея",
        ["Map.View"] = "Қарау",

        ["About.PageTitle"] = "Жоба туралы",
        ["About.Subtitle"] = "Алматыны жақсарту үшін азаматтық платформа",
        ["About.MissionTag"] = "Миссия",
        ["About.MissionTitle"] = "Open Almaty Ideas дегеніміз не?",
        ["About.MissionText"] = "Алматы тұрғындары үшін жасалған азаматтық бастамалардың цифрлық платформасы. Қаланы жақсартудың үздік идеялары онда тұратындардан туады деп сенеміз. Платформа әрбір қала тұрғынына дауыс береді — идея ұсыну, басқаларды қолдау және бастамалардың іске асырылуын бақылау мүмкіндігі.",
        ["About.ProcessTag"] = "Үрдіс",
        ["About.ProcessTitle"] = "Бұл қалай жұмыс істейді?",
        ["About.Step1Title"] = "Тіркеліңіз",
        ["About.Step1Text"] = "Аккаунт жасаңыз — бір минутқа дейін уақыт алады",
        ["About.Step2Title"] = "Ұсыныс беріңіз",
        ["About.Step2Text"] = "Идеяны сипаттаңыз, аудан мен санатты көрсетіңіз",
        ["About.Step3Title"] = "Дауыс беріңіз",
        ["About.Step3Text"] = "Басқа қала тұрғындарының ұнаған идеяларын қолдаңыз",
        ["About.Step4Title"] = "Нәтижені қадағалаңыз",
        ["About.Step4Text"] = "Әкімшілер ұсыныстарды қарастырып, мәртебені жаңартады",
        ["About.CoverageTag"] = "Қамту",
        ["About.DistrictsTitle"] = "Алматы аудандары",
        ["About.DistrictsText"] = "Платформа қаланың барлық 8 әкімшілік ауданын қамтиды:",
        ["About.CategoriesTag"] = "Тақырып",
        ["About.CategoriesTitle"] = "Ұсыныс санаттары",
        ["About.LifecycleTag"] = "Өмірлік цикл",
        ["About.StatusesTitle"] = "Ұсыныс мәртебелері",
        ["About.Status.Pending"] = "Қарастыруда",
        ["About.Status.PendingDesc"] = "Ұсыныс алынды және зерттелуде",
        ["About.Status.Accepted"] = "Қабылданды",
        ["About.Status.AcceptedDesc"] = "Идея іске асыруға бекітілді",
        ["About.Status.Implemented"] = "Іске асырылды",
        ["About.Status.ImplementedDesc"] = "Ұсыныс іске асырылды",
        ["About.Status.Rejected"] = "Қабылданбады",
        ["About.Status.RejectedDesc"] = "Ұсыныс себептері түсіндіріліп қабылданбады",
        ["About.CtaTitle"] = "Open Almaty Ideas жобасына қосылыңыз",
        ["About.CtaSubtitle"] = "Сіздің дауысыңыз Алматы дамуы үшін маңызды",
        ["About.SignUp"] = "Тіркелу",
        ["About.ViewProposals"] = "Ұсыныстарды қарау",

        ["Admin.ToSite"] = "← Сайтқа",
        ["Admin.Logout"] = "Шығу",
        ["Admin.Management"] = "Басқару",
        ["Admin.Home"] = "Басты бет",
        ["Admin.Proposals"] = "Ұсыныстар",
        ["Admin.Districts"] = "Аудандар",
        ["Admin.Categories"] = "Санаттар",
        ["Admin.DashboardTitle"] = "Әкімші панелі",
        ["Admin.ProposalsDesc"] = "Азаматтардың ұсыныстарын басқару",
        ["Admin.DistrictsDesc"] = "Қала аудандарын басқару",
        ["Admin.CategoriesDesc"] = "Ұсыныс санаттарын басқару",
        ["Admin.Manage"] = "Басқару",
        ["Admin.ColId"] = "#",
        ["Admin.ColName"] = "Атауы",
        ["Admin.ColDistrict"] = "Аудан",
        ["Admin.ColCategory"] = "Санат",
        ["Admin.ColAuthor"] = "Автор",
        ["Admin.ColStatus"] = "Мәртебе",
        ["Admin.ColDate"] = "Күні",
        ["Admin.ColActions"] = "Әрекеттер",
        ["Admin.ColCount"] = "Ұсыныстар",
        ["Admin.Edit"] = "Өзгерту",
        ["Admin.Delete"] = "Жою",
        ["Admin.AddCategory"] = "+ Санат қосу",
        ["Admin.AddDistrict"] = "+ Аудан қосу",
        ["Admin.DeleteProposalConfirm"] = "Ұсынысты жою керек пе?",
        ["Admin.DeleteCategoryConfirm"] = "Санатты жою керек пе?",
        ["Admin.DeleteDistrictConfirm"] = "Ауданды жою керек пе?",
        ["Admin.EditProposalTitle"] = "Ұсынысты өңдеу",
        ["Admin.StatusLabel"] = "Мәртебе",
        ["Admin.AdminResponse"] = "Әкімші жауабы (міндетті емес)",
        ["Admin.AdminResponsePlaceholder"] = "Шешімге түсініктеме енгізіңіз...",
        ["Admin.Save"] = "Сақтау",
        ["Admin.Cancel"] = "Бас тарту",
        ["Admin.NewCategory"] = "Жаңа санат",
        ["Admin.EditCategory"] = "Санатты өңдеу",
        ["Admin.NewDistrict"] = "Жаңа аудан",
        ["Admin.EditDistrict"] = "Ауданды өңдеу",
        ["Admin.AccessDeniedTitle"] = "Рұқсат жоқ",
        ["Admin.AccessDeniedText"] = "Бұл бетті қарауға рұқсатыңыз жоқ.",
        ["Admin.ToHome"] = "Басты бетке",
    };

    public LocalizedString this[string name]
    {
        get
        {
            var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            var dict = culture == "kk" ? _kk : _ru;
            var found = dict.TryGetValue(name, out var value);
            return new LocalizedString(name, found ? value! : name, !found);
        }
    }

    public LocalizedString this[string name, params object[] arguments]
    {
        get
        {
            var ls = this[name];
            return new LocalizedString(name, string.Format(ls.Value, arguments), ls.ResourceNotFound);
        }
    }

    public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
    {
        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        var dict = culture == "kk" ? _kk : _ru;
        return dict.Select(kv => new LocalizedString(kv.Key, kv.Value));
    }
}
