using System.Globalization;
using Microsoft.Extensions.Localization;

namespace OpenAlmatyIdeas;

public class SharedResource { }

public class AppStringLocalizer : IStringLocalizer<SharedResource>
{
    private static readonly Dictionary<string, string> _ru = new()
    {
        ["Nav.Proposals"] = "Предложения",
        ["Nav.Top"] = "Топ идей",
        ["Nav.Map"] = "Карта",
        ["Nav.About"] = "О проекте",
        ["Nav.AdminPanel"] = "⚙ Панель",
        ["Nav.NewProposal"] = "+ Предложение",
        ["Nav.MyProposals"] = "Мои предложения",
        ["Nav.Logout"] = "Выйти",
        ["Nav.Login"] = "Войти",
        ["Nav.Register"] = "Регистрация",

        ["Status.Pending"] = "На рассмотрении",
        ["Status.Accepted"] = "Принято",
        ["Status.Rejected"] = "Отклонено",
        ["Status.Implemented"] = "Реализовано",

        ["Footer.Text"] = "Платформа гражданских инициатив Алматы",
        ["Footer.Author"] = "Ермекова Айнур Ардаковна",
        ["Footer.Institution"] = "КазУТБ им. К. Кулажанова",
        ["Footer.Program"] = "7M04144 — Государственное и местное управление",
        ["Footer.Dissertation"] = "Диссертационная работа",
        ["Footer.Location"] = "Алматы, Казахстан",

        ["Home.PageTitle"] = "Главная",
        ["Home.TagLine"] = "Современная цифровая платформа — Алматы",
        ["Home.HeroSubtitle"] = "Предлагайте идеи по улучшению города, голосуйте и следите за реализацией.",
        ["Home.SuggestIdea"] = "+ Предложить идею",
        ["Home.JoinUs"] = "Присоединиться",
        ["Home.ViewProposals"] = "Смотреть предложения →",
        ["Home.ViewProposalsPlain"] = "Смотреть предложения",
        ["Home.StatProposals"] = "Предложений",
        ["Home.StatDistricts"] = "Районов",
        ["Home.StatCategories"] = "Категорий",
        ["Home.RatingTag"] = "Рейтинг",
        ["Home.TopProposals"] = "Топ предложения",
        ["Home.TopSubtitle"] = "Самые поддерживаемые идеи горожан",
        ["Home.CoverageTag"] = "Охват",
        ["Home.DistrictsTitle"] = "Районы Алматы",
        ["Home.DistrictsSubtitle"] = "Все 8 административных районов города",
        ["Home.ProcessTag"] = "Процесс",
        ["Home.HowItWorks"] = "Как это работает?",
        ["Home.Step1Title"] = "Зарегистрируйтесь",
        ["Home.Step1Text"] = "Создайте аккаунт — это займёт меньше минуты",
        ["Home.Step2Title"] = "Подайте предложение",
        ["Home.Step2Text"] = "Опишите идею, укажите район и категорию",
        ["Home.Step3Title"] = "Голосуйте",
        ["Home.Step3Text"] = "Поддерживайте понравившиеся идеи горожан",
        ["Home.Step4Title"] = "Следите за результатом",
        ["Home.Step4Text"] = "Статус предложения обновляется администраторами",
        ["Home.JoinTag"] = "Присоединяйтесь",
        ["Home.CtaTitle"] = "Ваш голос важен для Алматы",
        ["Home.CtaSubtitle"] = "Зарегистрируйтесь, чтобы подавать предложения и голосовать за идеи горожан.",
        ["Home.SignUp"] = "Зарегистрироваться",

        ["Proposals.PageTitle"] = "Предложения",
        ["Proposals.Subtitle"] = "Идеи жителей Алматы по улучшению города",
        ["Proposals.NewBtn"] = "+ Новое предложение",
        ["Proposals.SearchPlaceholder"] = "🔍 Поиск по названию...",
        ["Proposals.AllDistricts"] = "Все районы",
        ["Proposals.AllCategories"] = "Все категории",
        ["Proposals.SortNew"] = "Новые",
        ["Proposals.SortPopular"] = "Популярные",
        ["Proposals.Apply"] = "Применить",
        ["Proposals.Reset"] = "✕ Сбросить",
        ["Proposals.NotFound"] = "Предложений не найдено.",
        ["Proposals.BeFirst"] = "Будьте первым!",
        ["Proposals.Shown"] = "Показано:",
        ["Proposals.ShownSuffix"] = "предложений",

        ["Proposal.Back"] = "← Все предложения",
        ["Proposal.Voting"] = "Голосование",
        ["Proposal.LoginToVote"] = "Войдите",
        ["Proposal.ToVote"] = ", чтобы проголосовать",
        ["Proposal.Info"] = "Информация",
        ["Proposal.Status"] = "Статус",
        ["Proposal.District"] = "Район",
        ["Proposal.Category"] = "Категория",
        ["Proposal.Author"] = "Автор",
        ["Proposal.Date"] = "Дата",
        ["Proposal.Edit"] = "✏ Редактировать",
        ["Proposal.Delete"] = "🗑 Удалить",
        ["Proposal.DeleteConfirm"] = "Удалить предложение?",
        ["Proposal.AdminResponses"] = "💬 Ответы администратора",

        ["NewProposal.Title"] = "Новое предложение",
        ["NewProposal.Subtitle"] = "Опишите вашу идею по улучшению города",
        ["NewProposal.NameLabel"] = "Название",
        ["NewProposal.NamePlaceholder"] = "Краткое название вашей идеи",
        ["NewProposal.DistrictLabel"] = "Район",
        ["NewProposal.DistrictDefault"] = "— Выберите район —",
        ["NewProposal.CategoryLabel"] = "Категория",
        ["NewProposal.CategoryDefault"] = "— Выберите категорию —",
        ["NewProposal.ShortDescLabel"] = "Краткое описание",
        ["NewProposal.ShortDescPlaceholder"] = "Кратко опишите вашу идею (отображается в списке)",
        ["NewProposal.FullDescLabel"] = "Полное описание",
        ["NewProposal.FullDescPlaceholder"] = "Подробно опишите предложение: проблему, решение, ожидаемый результат",
        ["NewProposal.Submit"] = "Отправить предложение",
        ["NewProposal.Cancel"] = "Отмена",

        ["EditProposal.Title"] = "Редактировать предложение",
        ["EditProposal.Subtitle"] = "Измените данные вашего предложения",
        ["EditProposal.SaveChanges"] = "Сохранить изменения",
        ["EditProposal.Cancel"] = "Отмена",

        ["Login.Title"] = "Вход",
        ["Login.Subtitle"] = "Войдите в свой аккаунт",
        ["Login.Username"] = "Имя пользователя",
        ["Login.Password"] = "Пароль",
        ["Login.RememberMe"] = "Запомнить меня",
        ["Login.Submit"] = "Войти",
        ["Login.NoAccount"] = "Нет аккаунта?",
        ["Login.SignUp"] = "Зарегистрироваться",

        ["Register.Title"] = "Регистрация",
        ["Register.Subtitle"] = "Присоединяйтесь к Open Almaty Ideas",
        ["Register.Username"] = "Имя пользователя",
        ["Register.Email"] = "Email",
        ["Register.Password"] = "Пароль",
        ["Register.ConfirmPassword"] = "Подтвердите пароль",
        ["Register.Submit"] = "Зарегистрироваться",
        ["Register.HaveAccount"] = "Уже есть аккаунт?",
        ["Register.Login"] = "Войти",

        ["Profile.Title"] = "Мои предложения",
        ["Profile.NewBtn"] = "+ Новое предложение",
        ["Profile.Empty"] = "У вас пока нет предложений",
        ["Profile.CreateFirst"] = "Создать первое предложение",
        ["Profile.ColName"] = "Название",
        ["Profile.ColDistrict"] = "Район",
        ["Profile.ColCategory"] = "Категория",
        ["Profile.ColStatus"] = "Статус",
        ["Profile.ColVotes"] = "Голоса",
        ["Profile.ColDate"] = "Дата",
        ["Profile.Total"] = "Всего:",
        ["Profile.TotalSuffix"] = "предложений",
        ["Profile.DeleteConfirm"] = "Удалить предложение?",

        ["Top.PageTitle"] = "Топ идей",
        ["Top.RatingTag"] = "Рейтинг",
        ["Top.Title"] = "🏆 Топ идей",
        ["Top.Subtitle"] = "Предложения с наибольшим количеством голосов",
        ["Top.NoVotes"] = "Голосований пока нет. Будьте первым!",

        ["Map.PageTitle"] = "Карта районов",
        ["Map.InteractiveTag"] = "Интерактивная карта",
        ["Map.Title"] = "🗺️ Карта районов Алматы",
        ["Map.Subtitle"] = "Выберите район, чтобы просмотреть идеи жителей",
        ["Map.IdeaWord1"] = "идея",
        ["Map.IdeaWord24"] = "идеи",
        ["Map.IdeaWordMany"] = "идей",
        ["Map.View"] = "Смотреть",

        ["Cat.Transport"] = "Транспорт",
        ["Cat.Ecology"] = "Экология",
        ["Cat.Infrastructure"] = "Инфраструктура",
        ["Cat.Security"] = "Безопасность",
        ["Cat.Education"] = "Образование",
        ["Cat.Health"] = "Здравоохранение",
        ["Cat.Culture"] = "Культура и спорт",
        ["Cat.Other"] = "Другое",

        ["About.PageTitle"] = "О проекте",
        ["About.Subtitle"] = "Современная цифровая платформа для активного участия граждан в городском управлении",
        ["About.WhatIsTag"] = "Платформа",
        ["About.WhatIsTitle"] = "Что такое Open Almaty Ideas?",
        ["About.WhatIsText"] = "современная цифровая платформа, обеспечивающая активное участие граждан в процессе городского управления. Платформа собирает, анализирует и систематизирует предложения жителей в сферах городской инфраструктуры, экологии, транспорта, безопасности и социальной жизни, включая общественное мнение в процесс принятия решений с помощью цифровых технологий.",
        ["About.RelevanceTag"] = "Актуальность",
        ["About.RelevanceTitle"] = "Решаемые проблемы",
        ["About.Relevance1"] = "Необходимость цифровизации государственного управления",
        ["About.Relevance2"] = "Недостаточное участие граждан в принятии решений",
        ["About.Relevance3"] = "Слабая обратная связь между жителями и органами власти",
        ["About.Relevance4"] = "Переход к моделям управления, основанным на данных",
        ["About.InnovationTag"] = "Инновационность",
        ["About.InnovationTitle"] = "Инновационные направления",
        ["About.Innovation1Title"] = "Цифровой сбор",
        ["About.Innovation1Text"] = "Сбор и анализ гражданских предложений в цифровом формате",
        ["About.Innovation2Title"] = "Решения на основе данных",
        ["About.Innovation2Text"] = "Принятие управленческих решений на базе реальных данных от жителей",
        ["About.Innovation3Title"] = "Региональная платформа",
        ["About.Innovation3Text"] = "Масштабируемая модель цифрового участия для других регионов Казахстана",
        ["About.Innovation4Title"] = "Интерактивная коммуникация",
        ["About.Innovation4Text"] = "Диалог между гражданами и местными органами власти в режиме онлайн",
        ["About.ResultsTag"] = "Результаты",
        ["About.ResultsTitle"] = "Ожидаемые результаты",
        ["About.Result1"] = "Повышение уровня участия граждан в городском управлении",
        ["About.Result2"] = "Укрепление прозрачности и подотчётности органов власти",
        ["About.Result3"] = "Улучшение качества принимаемых управленческих решений",
        ["About.Result4"] = "Повышение эффективности решения городских проблем",
        ["About.MissionTag"] = "Миссия",
        ["About.MissionTitle"] = "Миссия и цели",
        ["About.MissionText"] = "Обеспечить эффективную обратную связь между жителями Алматы и органами местного самоуправления. Вовлечь горожан в решение городских проблем и обеспечить принятие качественных решений на основе их предложений.",
        ["About.ProcessTag"] = "Процесс",
        ["About.ProcessTitle"] = "Как это работает?",
        ["About.Step1Title"] = "Зарегистрируйтесь",
        ["About.Step1Text"] = "Создайте аккаунт с именем пользователя и email",
        ["About.Step2Title"] = "Подайте предложение",
        ["About.Step2Text"] = "Опишите идею, укажите район, категорию, добавьте фото или видео",
        ["About.Step3Title"] = "Голосуйте",
        ["About.Step3Text"] = "Оценивайте предложения других жителей лайками и дизлайками",
        ["About.Step4Title"] = "Следите за результатом",
        ["About.Step4Text"] = "Лучшие идеи рассматриваются и реализуются администрацией города",
        ["About.CoverageTag"] = "Охват",
        ["About.DistrictsTitle"] = "Районы Алматы",
        ["About.DistrictsText"] = "Платформа охватывает все 8 административных районов города:",
        ["About.CategoriesTag"] = "Тематика",
        ["About.CategoriesTitle"] = "Категории предложений",
        ["About.LifecycleTag"] = "Жизненный цикл",
        ["About.StatusesTitle"] = "Статусы предложений",
        ["About.Status.Pending"] = "На рассмотрении",
        ["About.Status.PendingDesc"] = "Предложение получено и изучается",
        ["About.Status.Accepted"] = "Принято",
        ["About.Status.AcceptedDesc"] = "Идея одобрена к реализации",
        ["About.Status.Implemented"] = "Реализовано",
        ["About.Status.ImplementedDesc"] = "Предложение воплощено в жизнь",
        ["About.Status.Rejected"] = "Отклонено",
        ["About.Status.RejectedDesc"] = "Предложение не принято с объяснением причин",
        ["About.AuthorTag"] = "Об авторе",
        ["About.AuthorTitle"] = "Об авторе проекта",
        ["About.AuthorNameLabel"] = "Автор",
        ["About.AuthorName"] = "Ермекова Айнур Ардаковна",
        ["About.AuthorInstitutionLabel"] = "Учебное заведение",
        ["About.AuthorInstitution"] = "КазУТБ им. К. Кулажанова",
        ["About.AuthorProgramLabel"] = "Программа",
        ["About.AuthorProgram"] = "7M04144 — Государственное и местное управление",
        ["About.AuthorNoteLabel"] = "Контекст",
        ["About.AuthorNote"] = "Разработано в рамках докторской диссертации",
        ["About.CtaTitle"] = "Присоединяйтесь к Open Almaty Ideas",
        ["About.CtaSubtitle"] = "Зарегистрируйтесь сегодня и внесите вклад в будущее Алматы",
        ["About.SignUp"] = "Зарегистрироваться",
        ["About.ViewProposals"] = "Смотреть предложения",

        ["Admin.ToSite"] = "← На сайт",
        ["Admin.Logout"] = "Выйти",
        ["Admin.Management"] = "Управление",
        ["Admin.Home"] = "Главная",
        ["Admin.Proposals"] = "Предложения",
        ["Admin.Districts"] = "Районы",
        ["Admin.Categories"] = "Категории",
        ["Admin.DashboardTitle"] = "Панель администратора",
        ["Admin.ProposalsDesc"] = "Управление предложениями граждан",
        ["Admin.DistrictsDesc"] = "Управление районами города",
        ["Admin.CategoriesDesc"] = "Управление категориями предложений",
        ["Admin.Manage"] = "Управлять",
        ["Admin.ColId"] = "#",
        ["Admin.ColName"] = "Название",
        ["Admin.ColDistrict"] = "Район",
        ["Admin.ColCategory"] = "Категория",
        ["Admin.ColAuthor"] = "Автор",
        ["Admin.ColStatus"] = "Статус",
        ["Admin.ColDate"] = "Дата",
        ["Admin.ColActions"] = "Действия",
        ["Admin.ColCount"] = "Предложений",
        ["Admin.Edit"] = "Изменить",
        ["Admin.Delete"] = "Удалить",
        ["Admin.AddCategory"] = "+ Добавить категорию",
        ["Admin.AddDistrict"] = "+ Добавить район",
        ["Admin.DeleteProposalConfirm"] = "Удалить предложение?",
        ["Admin.DeleteCategoryConfirm"] = "Удалить категорию?",
        ["Admin.DeleteDistrictConfirm"] = "Удалить район?",
        ["Admin.EditProposalTitle"] = "Редактирование предложения",
        ["Admin.StatusLabel"] = "Статус",
        ["Admin.AdminResponse"] = "Ответ администратора (необязательно)",
        ["Admin.AdminResponsePlaceholder"] = "Введите комментарий к решению...",
        ["Admin.Save"] = "Сохранить",
        ["Admin.Cancel"] = "Отмена",
        ["Admin.NewCategory"] = "Новая категория",
        ["Admin.EditCategory"] = "Редактирование категории",
        ["Admin.NewDistrict"] = "Новый район",
        ["Admin.EditDistrict"] = "Редактирование района",
        ["Admin.AccessDeniedTitle"] = "Доступ запрещён",
        ["Admin.AccessDeniedText"] = "У вас нет прав для просмотра этой страницы.",
        ["Admin.ToHome"] = "На главную",
    };

    private static readonly Dictionary<string, string> _kk = new()
    {
        ["Nav.Proposals"] = "Ұсыныстар",
        ["Nav.Top"] = "Идеялар топы",
        ["Nav.Map"] = "Карта",
        ["Nav.About"] = "Жоба туралы",
        ["Nav.AdminPanel"] = "⚙ Панель",
        ["Nav.NewProposal"] = "+ Ұсыныс",
        ["Nav.MyProposals"] = "Менің ұсыныстарым",
        ["Nav.Logout"] = "Шығу",
        ["Nav.Login"] = "Кіру",
        ["Nav.Register"] = "Тіркелу",

        ["Status.Pending"] = "Қарастыруда",
        ["Status.Accepted"] = "Қабылданды",
        ["Status.Rejected"] = "Қабылданбады",
        ["Status.Implemented"] = "Іске асырылды",

        ["Footer.Text"] = "Алматы азаматтық бастамалар платформасы",
        ["Footer.Author"] = "Ермекова Айнур Ардаковна",
        ["Footer.Institution"] = "Қ. Құлажанов атындағы КазУТБ",
        ["Footer.Program"] = "7M04144 — Мемлекеттік және жергілікті басқару",
        ["Footer.Dissertation"] = "Диссертациялық жұмыс",
        ["Footer.Location"] = "Алматы, Қазақстан",

        ["Home.PageTitle"] = "Басты бет",
        ["Home.TagLine"] = "Алматы қаласының тұрғындарына арналған заманауи цифрлық платформа",
        ["Home.HeroSubtitle"] = "Қаланы жақсарту туралы идеяларыңызды ұсыныңыз, дауыс беріңіз және іске асырылуын қадағалаңыз.",
        ["Home.SuggestIdea"] = "+ Идея ұсыну",
        ["Home.JoinUs"] = "Қосылу",
        ["Home.ViewProposals"] = "Ұсыныстарды қарау →",
        ["Home.ViewProposalsPlain"] = "Ұсыныстарды қарау",
        ["Home.StatProposals"] = "Ұсыныстар",
        ["Home.StatDistricts"] = "Аудандар",
        ["Home.StatCategories"] = "Санаттар",
        ["Home.RatingTag"] = "Рейтинг",
        ["Home.TopProposals"] = "Топ ұсыныстар",
        ["Home.TopSubtitle"] = "Қала тұрғындарының ең қолдауға ие идеялары",
        ["Home.CoverageTag"] = "Қамту",
        ["Home.DistrictsTitle"] = "Алматы аудандары",
        ["Home.DistrictsSubtitle"] = "Қаланың барлық 8 әкімшілік ауданы",
        ["Home.ProcessTag"] = "Үрдіс",
        ["Home.HowItWorks"] = "Бұл қалай жұмыс істейді?",
        ["Home.Step1Title"] = "Тіркеліңіз",
        ["Home.Step1Text"] = "Аккаунт жасаңыз — бір минутқа дейін уақыт алады",
        ["Home.Step2Title"] = "Ұсыныс беріңіз",
        ["Home.Step2Text"] = "Идеяны сипаттаңыз, аудан мен санатты көрсетіңіз",
        ["Home.Step3Title"] = "Дауыс беріңіз",
        ["Home.Step3Text"] = "Қала тұрғындарының ұнаған идеяларын қолдаңыз",
        ["Home.Step4Title"] = "Нәтижені қадағалаңыз",
        ["Home.Step4Text"] = "Ұсыныс мәртебесін әкімшілер жаңартады",
        ["Home.JoinTag"] = "Қосылыңыз",
        ["Home.CtaTitle"] = "Сіздің дауысыңыз Алматы үшін маңызды",
        ["Home.CtaSubtitle"] = "Ұсыныстар беру және қала тұрғындарының идеяларына дауыс беру үшін тіркеліңіз.",
        ["Home.SignUp"] = "Тіркелу",

        ["Proposals.PageTitle"] = "Ұсыныстар",
        ["Proposals.Subtitle"] = "Алматы тұрғындарының қаланы жақсарту идеялары",
        ["Proposals.NewBtn"] = "+ Жаңа ұсыныс",
        ["Proposals.SearchPlaceholder"] = "🔍 Атауы бойынша іздеу...",
        ["Proposals.AllDistricts"] = "Барлық аудандар",
        ["Proposals.AllCategories"] = "Барлық санаттар",
        ["Proposals.SortNew"] = "Жаңалар",
        ["Proposals.SortPopular"] = "Танымалдар",
        ["Proposals.Apply"] = "Қолдану",
        ["Proposals.Reset"] = "✕ Тазалау",
        ["Proposals.NotFound"] = "Ұсыныс табылмады.",
        ["Proposals.BeFirst"] = "Бірінші болыңыз!",
        ["Proposals.Shown"] = "Көрсетілген:",
        ["Proposals.ShownSuffix"] = "ұсыныс",

        ["Proposal.Back"] = "← Барлық ұсыныстар",
        ["Proposal.Voting"] = "Дауыс беру",
        ["Proposal.LoginToVote"] = "Кіріңіз",
        ["Proposal.ToVote"] = ", дауыс беру үшін",
        ["Proposal.Info"] = "Ақпарат",
        ["Proposal.Status"] = "Мәртебе",
        ["Proposal.District"] = "Аудан",
        ["Proposal.Category"] = "Санат",
        ["Proposal.Author"] = "Автор",
        ["Proposal.Date"] = "Күні",
        ["Proposal.Edit"] = "✏ Өңдеу",
        ["Proposal.Delete"] = "🗑 Жою",
        ["Proposal.DeleteConfirm"] = "Ұсынысты жою керек пе?",
        ["Proposal.AdminResponses"] = "💬 Әкімші жауаптары",

        ["NewProposal.Title"] = "Жаңа ұсыныс",
        ["NewProposal.Subtitle"] = "Қаланы жақсарту идеяңызды сипаттаңыз",
        ["NewProposal.NameLabel"] = "Атауы",
        ["NewProposal.NamePlaceholder"] = "Идеяңыздың қысқаша атауы",
        ["NewProposal.DistrictLabel"] = "Аудан",
        ["NewProposal.DistrictDefault"] = "— Аудан таңдаңыз —",
        ["NewProposal.CategoryLabel"] = "Санат",
        ["NewProposal.CategoryDefault"] = "— Санат таңдаңыз —",
        ["NewProposal.ShortDescLabel"] = "Қысқаша сипаттама",
        ["NewProposal.ShortDescPlaceholder"] = "Идеяңызды қысқаша сипаттаңыз (тізімде көрсетіледі)",
        ["NewProposal.FullDescLabel"] = "Толық сипаттама",
        ["NewProposal.FullDescPlaceholder"] = "Ұсынысты толық сипаттаңыз: мәселе, шешім, күтілетін нәтиже",
        ["NewProposal.Submit"] = "Ұсынысты жіберу",
        ["NewProposal.Cancel"] = "Бас тарту",

        ["EditProposal.Title"] = "Ұсынысты өңдеу",
        ["EditProposal.Subtitle"] = "Ұсыныс деректерін өзгертіңіз",
        ["EditProposal.SaveChanges"] = "Өзгерістерді сақтау",
        ["EditProposal.Cancel"] = "Бас тарту",

        ["Login.Title"] = "Кіру",
        ["Login.Subtitle"] = "Аккаунтыңызға кіріңіз",
        ["Login.Username"] = "Пайдаланушы аты",
        ["Login.Password"] = "Құпия сөз",
        ["Login.RememberMe"] = "Мені есте сақтау",
        ["Login.Submit"] = "Кіру",
        ["Login.NoAccount"] = "Аккаунт жоқ па?",
        ["Login.SignUp"] = "Тіркелу",

        ["Register.Title"] = "Тіркелу",
        ["Register.Subtitle"] = "Open Almaty Ideas жобасына қосылыңыз",
        ["Register.Username"] = "Пайдаланушы аты",
        ["Register.Email"] = "Email",
        ["Register.Password"] = "Құпия сөз",
        ["Register.ConfirmPassword"] = "Құпия сөзді растаңыз",
        ["Register.Submit"] = "Тіркелу",
        ["Register.HaveAccount"] = "Аккаунт бар ма?",
        ["Register.Login"] = "Кіру",

        ["Profile.Title"] = "Менің ұсыныстарым",
        ["Profile.NewBtn"] = "+ Жаңа ұсыныс",
        ["Profile.Empty"] = "Сізде әлі ұсыныс жоқ",
        ["Profile.CreateFirst"] = "Бірінші ұсынысты жасау",
        ["Profile.ColName"] = "Атауы",
        ["Profile.ColDistrict"] = "Аудан",
        ["Profile.ColCategory"] = "Санат",
        ["Profile.ColStatus"] = "Мәртебе",
        ["Profile.ColVotes"] = "Дауыстар",
        ["Profile.ColDate"] = "Күні",
        ["Profile.Total"] = "Барлығы:",
        ["Profile.TotalSuffix"] = "ұсыныс",
        ["Profile.DeleteConfirm"] = "Ұсынысты жою керек пе?",

        ["Top.PageTitle"] = "Идеялар топы",
        ["Top.RatingTag"] = "Рейтинг",
        ["Top.Title"] = "🏆 Идеялар топы",
        ["Top.Subtitle"] = "Ең көп дауыс жинаған ұсыныстар",
        ["Top.NoVotes"] = "Дауыс беру әлі жоқ. Бірінші болыңыз!",

        ["Map.PageTitle"] = "Аудандар картасы",
        ["Map.InteractiveTag"] = "Интерактивті карта",
        ["Map.Title"] = "🗺️ Алматы аудандарының картасы",
        ["Map.Subtitle"] = "Тұрғындардың идеяларын қарау үшін аудан таңдаңыз",
        ["Map.IdeaWord1"] = "идея",
        ["Map.IdeaWord24"] = "идея",
        ["Map.IdeaWordMany"] = "идея",
        ["Map.View"] = "Қарау",

        ["Cat.Transport"] = "Көлік",
        ["Cat.Ecology"] = "Экология",
        ["Cat.Infrastructure"] = "Инфрақұрылым",
        ["Cat.Security"] = "Қауіпсіздік",
        ["Cat.Education"] = "Білім",
        ["Cat.Health"] = "Денсаулық сақтау",
        ["Cat.Culture"] = "Мәдениет және спорт",
        ["Cat.Other"] = "Басқа",

        ["About.PageTitle"] = "Жоба туралы",
        ["About.Subtitle"] = "Азаматтардың қалалық басқарудағы белсенді қатысуын қамтамасыз ететін заманауи цифрлық платформа",
        ["About.WhatIsTag"] = "Платформа",
        ["About.WhatIsTitle"] = "Open Almaty Ideas дегеніміз не?",
        ["About.WhatIsText"] = "азаматтардың қалалық басқару процесіне белсенді қатысуын қамтамасыз ететін заманауи цифрлық платформа. Платформа қала инфрақұрылымы, экология, көлік, қауіпсіздік және әлеуметтік салалардағы тұрғындардың ұсыныстарын жинап, талдайды және жүйелейді, цифрлық технологиялар арқылы шешім қабылдау процесіне қоғамдық пікірді енгізеді.",
        ["About.RelevanceTag"] = "Өзектілік",
        ["About.RelevanceTitle"] = "Шешілетін мәселелер",
        ["About.Relevance1"] = "Мемлекеттік басқаруды цифрландыру қажеттілігі",
        ["About.Relevance2"] = "Азаматтардың шешім қабылдауға жеткіліксіз қатысуы",
        ["About.Relevance3"] = "Тұрғындар мен билік органдарының арасындағы кері байланыстың әлсіздігі",
        ["About.Relevance4"] = "Деректерге негізделген басқару үлгілеріне өту",
        ["About.InnovationTag"] = "Инновациялылық",
        ["About.InnovationTitle"] = "Инновациялық бағыттар",
        ["About.Innovation1Title"] = "Цифрлық жинақ",
        ["About.Innovation1Text"] = "Азаматтық ұсыныстарды цифрлық форматта жинақтау және талдау",
        ["About.Innovation2Title"] = "Деректерге негізделген шешімдер",
        ["About.Innovation2Text"] = "Тұрғындардың нақты деректері негізінде басқарушылық шешімдер қабылдау",
        ["About.Innovation3Title"] = "Аймақтық платформа",
        ["About.Innovation3Text"] = "Қазақстанның басқа аймақтарына арналған масштабталатын цифрлық қатысу моделі",
        ["About.Innovation4Title"] = "Интерактивті байланыс",
        ["About.Innovation4Text"] = "Азаматтар мен жергілікті билік органдарының арасындағы онлайн диалог",
        ["About.ResultsTag"] = "Нәтижелер",
        ["About.ResultsTitle"] = "Күтілетін нәтижелер",
        ["About.Result1"] = "Азаматтардың қалалық басқаруға қатысу деңгейін арттыру",
        ["About.Result2"] = "Билік органдарының ашықтығы мен есептілігін нығайту",
        ["About.Result3"] = "Қабылданатын басқарушылық шешімдердің сапасын жақсарту",
        ["About.Result4"] = "Қалалық мәселелерді шешу тиімділігін арттыру",
        ["About.MissionTag"] = "Миссия",
        ["About.MissionTitle"] = "Миссия мен мақсаттар",
        ["About.MissionText"] = "Алматы тұрғындары мен жергілікті өзін-өзі басқару органдарының арасында тиімді кері байланысты қамтамасыз ету. Қала тұрғындарын қалалық мәселелерді шешуге тарту және олардың ұсыныстары негізінде сапалы шешімдер қабылдауды қамтамасыз ету.",
        ["About.ProcessTag"] = "Үрдіс",
        ["About.ProcessTitle"] = "Бұл қалай жұмыс істейді?",
        ["About.Step1Title"] = "Тіркеліңіз",
        ["About.Step1Text"] = "Пайдаланушы аты мен email арқылы аккаунт жасаңыз",
        ["About.Step2Title"] = "Ұсыныс беріңіз",
        ["About.Step2Text"] = "Идеяны сипаттаңыз, аудан, санат, фото немесе бейне қосыңыз",
        ["About.Step3Title"] = "Дауыс беріңіз",
        ["About.Step3Text"] = "Басқа тұрғындардың ұсыныстарын лайк және дизлайк арқылы бағалаңыз",
        ["About.Step4Title"] = "Нәтижені қадағалаңыз",
        ["About.Step4Text"] = "Үздік идеяларды қала әкімшілігі қарастырып, іске асырады",
        ["About.CoverageTag"] = "Қамту",
        ["About.DistrictsTitle"] = "Алматы аудандары",
        ["About.DistrictsText"] = "Платформа қаланың барлық 8 әкімшілік ауданын қамтиды:",
        ["About.CategoriesTag"] = "Тақырып",
        ["About.CategoriesTitle"] = "Ұсыныс санаттары",
        ["About.LifecycleTag"] = "Өмірлік цикл",
        ["About.StatusesTitle"] = "Ұсыныс мәртебелері",
        ["About.Status.Pending"] = "Қарастыруда",
        ["About.Status.PendingDesc"] = "Ұсыныс алынды және зерттелуде",
        ["About.Status.Accepted"] = "Қабылданды",
        ["About.Status.AcceptedDesc"] = "Идея іске асыруға бекітілді",
        ["About.Status.Implemented"] = "Іске асырылды",
        ["About.Status.ImplementedDesc"] = "Ұсыныс іске асырылды",
        ["About.Status.Rejected"] = "Қабылданбады",
        ["About.Status.RejectedDesc"] = "Ұсыныс себептері түсіндіріліп қабылданбады",
        ["About.AuthorTag"] = "Автор туралы",
        ["About.AuthorTitle"] = "Жоба авторы туралы",
        ["About.AuthorNameLabel"] = "Автор",
        ["About.AuthorName"] = "Ермекова Айнур Ардаковна",
        ["About.AuthorInstitutionLabel"] = "Оқу орны",
        ["About.AuthorInstitution"] = "Қ. Құлажанов атындағы КазУТБ",
        ["About.AuthorProgramLabel"] = "Бағдарлама",
        ["About.AuthorProgram"] = "7M04144 — Мемлекеттік және жергілікті басқару",
        ["About.AuthorNoteLabel"] = "Контекст",
        ["About.AuthorNote"] = "Докторлық диссертация жұмысы аясында жасалған",
        ["About.CtaTitle"] = "Open Almaty Ideas жобасына қосылыңыз",
        ["About.CtaSubtitle"] = "Бүгін тіркеліп, Алматының болашағына үлес қосыңыз",
        ["About.SignUp"] = "Тіркелу",
        ["About.ViewProposals"] = "Ұсыныстарды қарау",

        ["Admin.ToSite"] = "← Сайтқа",
        ["Admin.Logout"] = "Шығу",
        ["Admin.Management"] = "Басқару",
        ["Admin.Home"] = "Басты бет",
        ["Admin.Proposals"] = "Ұсыныстар",
        ["Admin.Districts"] = "Аудандар",
        ["Admin.Categories"] = "Санаттар",
        ["Admin.DashboardTitle"] = "Әкімші панелі",
        ["Admin.ProposalsDesc"] = "Азаматтардың ұсыныстарын басқару",
        ["Admin.DistrictsDesc"] = "Қала аудандарын басқару",
        ["Admin.CategoriesDesc"] = "Ұсыныс санаттарын басқару",
        ["Admin.Manage"] = "Басқару",
        ["Admin.ColId"] = "#",
        ["Admin.ColName"] = "Атауы",
        ["Admin.ColDistrict"] = "Аудан",
        ["Admin.ColCategory"] = "Санат",
        ["Admin.ColAuthor"] = "Автор",
        ["Admin.ColStatus"] = "Мәртебе",
        ["Admin.ColDate"] = "Күні",
        ["Admin.ColActions"] = "Әрекеттер",
        ["Admin.ColCount"] = "Ұсыныстар",
        ["Admin.Edit"] = "Өзгерту",
        ["Admin.Delete"] = "Жою",
        ["Admin.AddCategory"] = "+ Санат қосу",
        ["Admin.AddDistrict"] = "+ Аудан қосу",
        ["Admin.DeleteProposalConfirm"] = "Ұсынысты жою керек пе?",
        ["Admin.DeleteCategoryConfirm"] = "Санатты жою керек пе?",
        ["Admin.DeleteDistrictConfirm"] = "Ауданды жою керек пе?",
        ["Admin.EditProposalTitle"] = "Ұсынысты өңдеу",
        ["Admin.StatusLabel"] = "Мәртебе",
        ["Admin.AdminResponse"] = "Әкімші жауабы (міндетті емес)",
        ["Admin.AdminResponsePlaceholder"] = "Шешімге түсініктеме енгізіңіз...",
        ["Admin.Save"] = "Сақтау",
        ["Admin.Cancel"] = "Бас тарту",
        ["Admin.NewCategory"] = "Жаңа санат",
        ["Admin.EditCategory"] = "Санатты өңдеу",
        ["Admin.NewDistrict"] = "Жаңа аудан",
        ["Admin.EditDistrict"] = "Ауданды өңдеу",
        ["Admin.AccessDeniedTitle"] = "Рұқсат жоқ",
        ["Admin.AccessDeniedText"] = "Бұл бетті қарауға рұқсатыңыз жоқ.",
        ["Admin.ToHome"] = "Басты бетке",
    };

    public LocalizedString this[string name]
    {
        get
        {
            var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            var dict = culture == "kk" ? _kk : _ru;
            var found = dict.TryGetValue(name, out var value);
            return new LocalizedString(name, found ? value! : name, !found);
        }
    }

    public LocalizedString this[string name, params object[] arguments]
    {
        get
        {
            var ls = this[name];
            return new LocalizedString(name, string.Format(ls.Value, arguments), ls.ResourceNotFound);
        }
    }

    public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
    {
        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        var dict = culture == "kk" ? _kk : _ru;
        return dict.Select(kv => new LocalizedString(kv.Key, kv.Value));
    }
}
